<?php
require_once('../../_config.php');
$doxygen_title = "LocalJS: Class List";
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Class List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>Class List</h1>  </div>
</div>
<div class="contents">
Here are the classes, structs, unions and interfaces with brief descriptions:<table>
  <tr><td class="indexkey"><a class="el" href="interface_browser_window.php">BrowserWindow</a></td><td class="indexvalue">Open source object. Represents a browser window. Returned by <a class="el" href="interface_u_i.php#a1affe0f3629c5b39d93ba05fd54fc3fc" title="Creates a new browser window or standalone Internet Explorer and navigates to given url...">UI.newWindow</a>. Include localjs_ui.js to use it </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_buffer.php">Buffer</a></td><td class="indexvalue"><a class="el" href="interface_buffer.php" title="Buffer object represents a fixed size buffer, used as parameters in Dll function call.">Buffer</a> object represents a fixed size buffer, used as parameters in Dll function call </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_c_o_m.php">COM</a></td><td class="indexvalue">Object <a class="el" href="interface_c_o_m.php" title="Object COM exposes methods to create COM object, connect COM events, etc.">COM</a> exposes methods to create COM object, connect COM events, etc </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_dll_call.php">DllCall</a></td><td class="indexvalue"><a class="el" href="interface_dll_call.php" title="DllCall object enables JavaScript call functions exported by DLL or EXE files, including most Windows...">DllCall</a> object enables JavaScript call functions exported by DLL or EXE files, including most Windows API functions </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_enumerator.php">Enumerator</a></td><td class="indexvalue">Similar to <a href="http://msdn.microsoft.com/en-us/library/6ch9zb09(VS.85).aspx" target="_blank">Enumerator object in JScript</a>, providing access to items in Collection object </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_event_hook.php">EventHook</a></td><td class="indexvalue">Returned by method <a class="el" href="interface_c_o_m.php#a03b548ce8da020a692d590d4a5b21247" title="Connect JavaScript functions to COM object events.">COM.connectEvents</a>, used to disconnect COM event connected </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_f_i_l_e.php">FILE</a></td><td class="indexvalue">Open source object. Provides methods for common file and registry operations. Include localjs_file.js, localjs_ui.js and localjs_webservice.js to use it </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a></td><td class="indexvalue">Open source object. Provides method for multi-languages support. Include localjs_localization.js, localjs_file.js, localjs_ui.js and localjs_webservice.js to use it </td></tr>
  <tr><td class="indexkey"><a class="el" href="interfacelocal_j_s.php">localJS</a></td><td class="indexvalue">The root object of all advanced JavaScript objects. <em>Available directly in JavaScript.</em> </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_l_o_c_a_l_j_s.php">LOCALJS</a></td><td class="indexvalue">The root object of all LocalJS Basic objects. Need to include JavaScript files from LOCALJS Open Source Library to be available </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_structure.php">Structure</a></td><td class="indexvalue"><a class="el" href="interface_structure.php" title="Structure object represents a C struct, used as parameters in Dll function call.">Structure</a> object represents a C struct, used as parameters in Dll function call </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_thread.php">Thread</a></td><td class="indexvalue">Represent a script thread </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_threading.php">Threading</a></td><td class="indexvalue"><a class="el" href="interface_threading.php" title="Threading object exposes methods to create new script thread, sleep, get thread id, etc.">Threading</a> object exposes methods to create new script thread, sleep, get thread id, etc </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_u_i.php">UI</a></td><td class="indexvalue">Open source object. Provides methods for common UI operations. Include localjs_ui.js to use it </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_w_e_b___s_e_r_v_i_c_e.php">WEB_SERVICE</a></td><td class="indexvalue">Open source object. Provides method for web service call. Include localjs_webservice.js to use it </td></tr>
  <tr><td class="indexkey"><a class="el" href="interface_window_hook.php">WindowHook</a></td><td class="indexvalue">Hook messages of the specified window </td></tr>
</table>
</div>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
