<?php
require_once('../../_config.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<?php include_once($base_path.'/_include/common_header_part1.php'); ?>
<title>LocalJS: Member List</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>fonts/fonts-min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>grids/grids-min.css"/>
<?php include_once($base_path.'/_include/common_header_part2.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Home</span></a></li>
      <li><a href="pages.php"><span>Getting&#160;Started</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Structure Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_structure.php">Structure</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a0ce42643bb28edae3ef95829c7257d18">add</a>(Structure/Buffer/address field,[optional] String fieldName)</td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a9823b3580b74ed81cf6542b5df88eff1">addByte</a>([optional] byte initialValue,[optional] String fieldName)</td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a9281de28bee204692288a33173e38568">addLong</a>([optional] long initialValue,[optional] String fieldName)</td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a6fb29719905b419d362cb7db84fc363c">addLongLong</a>([optional] __int64 initialValue,[optional] String fieldName)</td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a948cb08f27bc32eb7afdd80cfc6f0486">address</a></td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#add3df9b88b7ecc45ee30cd9969020c28">addShort</a>([optional] short initialValue,[optional] String fieldName)</td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#aa993855d0ffaf23f5d40f784cadc4ee0">clone</a>()</td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a9fd5a67375c442dddcf84e715abc92a8">field</a></td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a6725042366a2566ebaeecd8d267859ac">fieldCount</a></td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_structure.php#a37363161b41c4165b98cba7abc7a9d95">size</a></td><td><a class="el" href="interface_structure.php">Structure</a></td><td></td></tr>
</table></div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
