<?php
require_once('../../_config.php');
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Member List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>DllCall Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_dll_call.php">DllCall</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_dll_call.php#ab6730ea57a7678c1f07953ce331edca0">add</a>(String dllPath, String prototype,[optional] String renameTo)</td><td><a class="el" href="interface_dll_call.php">DllCall</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_dll_call.php#a3bdaadf97fcc30c6e0d280fe3926afa6">checkAdd</a></td><td><a class="el" href="interface_dll_call.php">DllCall</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_dll_call.php#af9c99ab123bbf569e623a9c5e5c9f40e">newBuffer</a>(int/String sizeOrString,[optional] int/boolean valueOrAnsi)</td><td><a class="el" href="interface_dll_call.php">DllCall</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_dll_call.php#ac5fb73dfc65171de9e56b090a56b1269">newStruct</a>()</td><td><a class="el" href="interface_dll_call.php">DllCall</a></td><td></td></tr>
</table></div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
