<?php
require_once('../../_config.php');
$doxygen_title = "LocalJS: Member List";
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Member List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>LOCALIZATION Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#ad28f052945833b0267c4353afcbf58eb">get</a>(String key)</td><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#a0162e8ff61641568734b65adec1ad183">getAcceptLanguages</a>()</td><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#ab8161b47b743b715de4683c838c60d4d">getLang</a>()</td><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#acaf64f0e414c32bfa3c5cee215b06373">setLang</a>(String lang,[optional] boolean reload)</td><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#a494b7408816f0e6545fe409d7f14a1a6">setPath</a>(String path,[optional] boolean reload)</td><td><a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php">LOCALIZATION</a></td><td></td></tr>
</table></div>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
