<?php
require_once('../../_config.php');
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Member List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>COM Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_c_o_m.php">COM</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_c_o_m.php#a03b548ce8da020a692d590d4a5b21247">connectEvents</a>(Object source, Object handler,[optional] boolean event_parameters_return_value)</td><td><a class="el" href="interface_c_o_m.php">COM</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_c_o_m.php#a14285e3676c39b414cac2652046ec881">createObject</a>(String progID,[optional] String location)</td><td><a class="el" href="interface_c_o_m.php">COM</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_c_o_m.php#aa5d75d3298d5de451ecbead91d92b32d">getObject</a>(String displayName,[optional] String progID)</td><td><a class="el" href="interface_c_o_m.php">COM</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_c_o_m.php#a9742cc74cdf0445008d4adb2adbaa0d3">interface2Object</a>(long rawPointer)</td><td><a class="el" href="interface_c_o_m.php">COM</a></td><td></td></tr>
</table></div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
