<?php
require_once('../../_config.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<?php include_once($base_path.'/_include/common_header_part1.php'); ?>
<title>LocalJS: Member List</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>fonts/fonts-min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>grids/grids-min.css"/>
<?php include_once($base_path.'/_include/common_header_part2.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Home</span></a></li>
      <li><a href="pages.php"><span>Getting&#160;Started</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>UI Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_u_i.php">UI</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#aed53a5a22874b3433e67982678c0d531">addDraggable</a>(var el,...)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#ab4f615fc494a1630d85d58ca37deb01a">bring2Top</a>()</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a23574b724ef4f4142a333c96a2cc59df">centerWindow</a>(int cx, int cy)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a8e8c34b33f063c99f3c36b7916e396b9">confirm</a>(String msg,[optional] boolean default_yes,[optional] boolean ok_cancel)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#ad3d9b6673410aa22403cbb513c55ee4a">doEvents</a>()</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a336a7e8690beb99db79da34c2a1f2810">exitCallback</a></td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a036ec67a95716f85c0be9e723ac4782d">getDraggables</a>()</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a8077b95470f71884d59a6d5f09f29b5b">getWindowPlacement</a>()</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#afe21d5b455eddf90a3260f387bb94379">getWindowRect</a>()</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a862ffbf6976d63755adc1fc78f1a0354">isIE</a></td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a48bb86d6512ddef0a89997f6f26b28bb">moveWindow</a>(int left, int top, int width, int height)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#ae4029da3a7b30a44c2a93b186146e3ae">msgBox</a>(String msg,[optional] boolean error)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a1affe0f3629c5b39d93ba05fd54fc3fc">newWindow</a>(String url,[optional] int left,[optional] int top,[optional] int width,[optional] int height,[optional] int window_style,[optional] int parent_window,[optional] function initFunction,[optional] boolean leave_alone,[optional] boolean ie)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a474aa92c6232d183575e5986f50a35a2">newWindowCallback</a></td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a07804c8c056dedcec3467bc1c9470db4">setDraggables</a>(array el_draggable_array)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a3fdde78a1c8ea2a61bac248bfc85e9df">setWindowPlacement</a>(Structure placement)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a8661d51c7e5389632e89177abfd92a45">showTitleBar</a>([optional] boolean hide)</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a733cb08eb4bc17051512573d8d67d388">updateTitle</a>()</td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a80375f6cbd4820b29a2a99a0fd75f8e0">WS_CLOSE_ONLY</a></td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a427576c9d7c9ec954db20eadde150301">WS_NO_TITLE_BAR</a></td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_u_i.php#a3f568fbb10b5e9901afe81d86c5d5989">WS_NORMAL</a></td><td><a class="el" href="interface_u_i.php">UI</a></td><td></td></tr>
</table></div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
