<?php
require_once('../../_config.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<?php include_once($base_path.'/_include/common_header_part1.php'); ?>
<title>LocalJS: Member List</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>fonts/fonts-min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>grids/grids-min.css"/>
<?php include_once($base_path.'/_include/common_header_part2.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Home</span></a></li>
      <li><a href="pages.php"><span>Getting&#160;Started</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="annotated.php"><span>Classes</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="annotated.php"><span>Class&#160;List</span></a></li>
      <li><a href="classes.php"><span>Class&#160;Index</span></a></li>
      <li><a href="functions.php"><span>Class&#160;Members</span></a></li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Thread Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_thread.php">Thread</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_thread.php#aa4c7e8ce5147b0a22d6f2543c017a937">detach</a>()</td><td><a class="el" href="interface_thread.php">Thread</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_thread.php#a61ce2a4d4a93bba3bc16271882996fc4">handle</a></td><td><a class="el" href="interface_thread.php">Thread</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_thread.php#a7350fbd6ad10618f3b750b1f99ca5c3c">id</a></td><td><a class="el" href="interface_thread.php">Thread</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_thread.php#a980d8518a01dac55c30b0fb2fb894eba">kill</a>()</td><td><a class="el" href="interface_thread.php">Thread</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_thread.php#a2bb58b88ac256b165a95a806ae3b41e5">running</a></td><td><a class="el" href="interface_thread.php">Thread</a></td><td></td></tr>
</table></div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
