<?php
require_once('../../_config.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<?php include_once($base_path.'/_include/common_header_part1.php'); ?>
<title>LocalJS: Class Members</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>fonts/fonts-min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>grids/grids-min.css"/>
<?php include_once($base_path.'/_include/common_header_part2.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Home</span></a></li>
      <li><a href="pages.php"><span>Getting&#160;Started</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li class="current"><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>
      </li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li class="current"><a href="namespacemembers.php"><span>Namespaces&#160;Members</span></a></li>
    </ul>
  </div>
  <div class="tabs2">
    <ul class="tablist">
      <li class="current"><a href="namespacemembers.php"><span>All</span></a></li>
      <li><a href="namespacemembers_func.php"><span>Functions</span></a></li>
    </ul>
  </div>
</div>
<div class="contents">
Here is a list of all documented namespace members with links to the namespaces they belong to:<ul>
<li>browserWindowClosed()
: <a class="el" href="group___host_a_p_i.php#ga2411f33e78c102a27ddd2c921ff03d35">LocalJSHostAPI</a>
</li>
<li>callJSFunction()
: <a class="el" href="group___host_a_p_i.php#ga779ed3a959cb0e21f8aad4b899bdb505">LocalJSHostAPI</a>
</li>
<li>callJSFunction_va_list()
: <a class="el" href="group___host_a_p_i.php#ga1cd8332c156b5897050189b2250dca2e">LocalJSHostAPI</a>
</li>
<li>createBrowserWindow()
: <a class="el" href="group___host_a_p_i.php#ga1ca250104d8e424d1af1fae979bea9d6">LocalJSHostAPI</a>
</li>
<li>createIE()
: <a class="el" href="group___host_a_p_i.php#ga392ee050a9bb4f8bc3a549498f2491c2">LocalJSHostAPI</a>
</li>
<li>deleteBrowserWindow()
: <a class="el" href="group___host_a_p_i.php#ga314b0a2593ed6d4c12248d2068082158">LocalJSHostAPI</a>
</li>
<li>detachBrowserWindow()
: <a class="el" href="group___host_a_p_i.php#gac47c4be12c58fe280e658329f798c141">LocalJSHostAPI</a>
</li>
<li>getBrowserHostWnd()
: <a class="el" href="group___host_a_p_i.php#ga8d6df87cf800c5be2e7be541b34c1317">LocalJSHostAPI</a>
</li>
<li>getBrowserObj()
: <a class="el" href="group___host_a_p_i.php#gad71e54ddf1d1fad062c95a5c9b574806">LocalJSHostAPI</a>
</li>
<li>getBrowserType()
: <a class="el" href="group___host_a_p_i.php#gaabaa683bb0dc2d56827f8369f594dff5">LocalJSHostAPI</a>
</li>
<li>getIETabWnd()
: <a class="el" href="group___host_a_p_i.php#ga0c446918df21860233f6543b19740ea0">LocalJSHostAPI</a>
</li>
<li>initializeLocalJS()
: <a class="el" href="group___host_a_p_i.php#ga2bda3d0035edca22e5fd7d3cbca3fa03">LocalJSHostAPI</a>
</li>
<li>setBrowserControlRegPath()
: <a class="el" href="group___host_a_p_i.php#ga7474b7f77001b41241fdadc926054645">LocalJSHostAPI</a>
</li>
<li>translateBrowserAccelerator()
: <a class="el" href="group___host_a_p_i.php#gaf4383b8a7a504809b0cee77f832bd27e">LocalJSHostAPI</a>
</li>
<li>uninitializeLocalJS()
: <a class="el" href="group___host_a_p_i.php#gac45d62dc3eb89dfd8715187967f9ccd5">LocalJSHostAPI</a>
</li>
</ul>
</div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
