<?php
require_once('../../_config.php');
$doxygen_title = "LocalJS: Package List";
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Package List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>Package List</h1>  </div>
</div>
<div class="contents">
Here are the packages with brief descriptions (if available):<table>
  <tr><td class="indexkey"><a class="el" href="namespace_local_j_s_host_a_p_i.php">LocalJSHostAPI</a></td><td class="indexvalue">C functions to launch and manage LocalJS browser windows, also available to JavaScript. Detailed in <a class="el" href="group___host_a_p_i.php">LocalJS Host API</a> </td></tr>
</table>
</div>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
