<?php
require_once('../../_config.php');
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Page Index</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>Related Pages</h1>  </div>
</div>
<div class="contents">
Here is a list of all related documentation pages:<ul>
<li><a class="el" href="howto.php">How To ...</a>
</li>
<li><a class="el" href="tutorial_js4cpp.php">JavaScript Jump Start For C++ Programmers</a>
</li>
</ul>
</div>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
