<?php
require_once('../../_config.php');
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Member List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>WEB_SERVICE Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_w_e_b___s_e_r_v_i_c_e.php">WEB_SERVICE</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_w_e_b___s_e_r_v_i_c_e.php#a7eb6ada1e0326fa0119b999ab83efd55">callUrl</a>(String http_method, String url,[optional] Object callback,[optional] String request_body,[optional] String username,[optional] String password)</td><td><a class="el" href="interface_w_e_b___s_e_r_v_i_c_e.php">WEB_SERVICE</a></td><td></td></tr>
</table></div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
