<?php
require_once('../../_config.php');
$doxygen_title = "LocalJS: Member List";
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Member List</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="header">
  <div class="headertitle">
<h1>Threading Member List</h1>  </div>
</div>
<div class="contents">
This is the complete list of members for <a class="el" href="interface_threading.php">Threading</a>, including all inherited members.<table>
  <tr class="memlist"><td><a class="el" href="interface_threading.php#ad28efcee5e8f0b2417a1776dc96365a6">currentThreadID</a></td><td><a class="el" href="interface_threading.php">Threading</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_threading.php#ab83b569dcb6b1ed35d6e9f13a8376a64">newThread</a>(String code,[optional] String language,[optional] var arguments)</td><td><a class="el" href="interface_threading.php">Threading</a></td><td></td></tr>
  <tr class="memlist"><td><a class="el" href="interface_threading.php#a2f94dee6d866d46d1f949359c765f704">sleep</a>(long milliseconds)</td><td><a class="el" href="interface_threading.php">Threading</a></td><td></td></tr>
</table></div>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
