<?php
require_once('../../_config.php');
include_once($base_path.'/_include/common_header_part1.php');
?>
<title>LocalJS: Class Members - Functions</title>
<?php include_once($base_path.'/_include/doxygen_header.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
  <div class="tabs2">
    <ul class="tablist">
      <li><a href="functions.php"><span>All</span></a></li>
      <li class="current"><a href="functions_func.php"><span>Functions</span></a></li>
      <li><a href="functions_prop.php"><span>Properties</span></a></li>
    </ul>
  </div>
  <div class="tabs3">
    <ul class="tablist">
      <li><a href="#index_a"><span>a</span></a></li>
      <li><a href="#index_b"><span>b</span></a></li>
      <li><a href="#index_c"><span>c</span></a></li>
      <li><a href="#index_d"><span>d</span></a></li>
      <li><a href="#index_e"><span>e</span></a></li>
      <li><a href="#index_f"><span>f</span></a></li>
      <li><a href="#index_g"><span>g</span></a></li>
      <li><a href="#index_h"><span>h</span></a></li>
      <li><a href="#index_i"><span>i</span></a></li>
      <li><a href="#index_k"><span>k</span></a></li>
      <li><a href="#index_l"><span>l</span></a></li>
      <li><a href="#index_m"><span>m</span></a></li>
      <li><a href="#index_n"><span>n</span></a></li>
      <li><a href="#index_p"><span>p</span></a></li>
      <li><a href="#index_r"><span>r</span></a></li>
      <li><a href="#index_s"><span>s</span></a></li>
      <li><a href="#index_t"><span>t</span></a></li>
      <li><a href="#index_u"><span>u</span></a></li>
      <li><a href="#index_w"><span>w</span></a></li>
    </ul>
  </div>
<div class="contents">
&#160;

<h3><a class="anchor" id="index_a"></a>- a -</h3><ul>
<li>add()
: <a class="el" href="interface_dll_call.php#ab6730ea57a7678c1f07953ce331edca0">DllCall</a>
, <a class="el" href="interface_structure.php#a0ce42643bb28edae3ef95829c7257d18">Structure</a>
</li>
<li>addByte()
: <a class="el" href="interface_structure.php#a9823b3580b74ed81cf6542b5df88eff1">Structure</a>
</li>
<li>addDraggable()
: <a class="el" href="interface_u_i.php#aed53a5a22874b3433e67982678c0d531">UI</a>
</li>
<li>addLong()
: <a class="el" href="interface_structure.php#a9281de28bee204692288a33173e38568">Structure</a>
</li>
<li>addLongLong()
: <a class="el" href="interface_structure.php#a6fb29719905b419d362cb7db84fc363c">Structure</a>
</li>
<li>addShort()
: <a class="el" href="interface_structure.php#add3df9b88b7ecc45ee30cd9969020c28">Structure</a>
</li>
<li>atEnd()
: <a class="el" href="interface_enumerator.php#ad8e6c6206cf37f968bbe6dbf187122ed">Enumerator</a>
</li>
</ul>


<h3><a class="anchor" id="index_b"></a>- b -</h3><ul>
<li>bring2Top()
: <a class="el" href="interface_u_i.php#ab4f615fc494a1630d85d58ca37deb01a">UI</a>
</li>
<li>browseFile()
: <a class="el" href="interface_f_i_l_e.php#a561e6ec182a20ebe1d85653d67b0ae44">FILE</a>
</li>
<li>browseFolder()
: <a class="el" href="interface_f_i_l_e.php#a5ddc249346092c53b6e0fadd644a0fb7">FILE</a>
</li>
<li>buildPath()
: <a class="el" href="interface_f_i_l_e.php#ab2be2bfa8a34bf9e4cc76064213c9240">FILE</a>
</li>
<li>buildUrl()
: <a class="el" href="interface_f_i_l_e.php#ab7cbd8e35cc7111c289225daf4696cea">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_c"></a>- c -</h3><ul>
<li>callDefaultWndProc()
: <a class="el" href="interface_window_hook.php#a1a92b100728f2a66ba2d2fe660857264">WindowHook</a>
</li>
<li>callOriginalWndProc()
: <a class="el" href="interface_window_hook.php#a85fe484b22d5d233c6b84c2b193e508a">WindowHook</a>
</li>
<li>callUrl()
: <a class="el" href="interface_w_e_b___s_e_r_v_i_c_e.php#a7eb6ada1e0326fa0119b999ab83efd55">WEB_SERVICE</a>
</li>
<li>centerWindow()
: <a class="el" href="interface_u_i.php#a23574b724ef4f4142a333c96a2cc59df">UI</a>
</li>
<li>clone()
: <a class="el" href="interface_buffer.php#ae92cd8c68053b3cd5197dfdd93f39529">Buffer</a>
, <a class="el" href="interface_structure.php#aa993855d0ffaf23f5d40f784cadc4ee0">Structure</a>
</li>
<li>close()
: <a class="el" href="interface_browser_window.php#aa69c8bf1f1dcf4e72552efff1fe3e87e">BrowserWindow</a>
</li>
<li>closeWindow()
: <a class="el" href="interfacelocal_j_s.php#ae0a273e38f45d2547157ddb6cfa6108c">localJS</a>
</li>
<li>confirm()
: <a class="el" href="interface_u_i.php#a8e8c34b33f063c99f3c36b7916e396b9">UI</a>
</li>
<li>connectEvents()
: <a class="el" href="interface_c_o_m.php#a03b548ce8da020a692d590d4a5b21247">COM</a>
</li>
<li>createFolder()
: <a class="el" href="interface_f_i_l_e.php#a11c4eb341be6b3dcf3f2ce9d855b058e">FILE</a>
</li>
<li>createObject()
: <a class="el" href="interface_c_o_m.php#a14285e3676c39b414cac2652046ec881">COM</a>
</li>
</ul>


<h3><a class="anchor" id="index_d"></a>- d -</h3><ul>
<li>deleteFile()
: <a class="el" href="interface_f_i_l_e.php#ae422d3995ad20fae50da0a6a5667654f">FILE</a>
</li>
<li>deleteFolder()
: <a class="el" href="interface_f_i_l_e.php#ac37bcb6da1316d7792a5491a2f7801a6">FILE</a>
</li>
<li>detach()
: <a class="el" href="interface_thread.php#aa4c7e8ce5147b0a22d6f2543c017a937">Thread</a>
</li>
<li>disconnect()
: <a class="el" href="interface_event_hook.php#abe175fcf658475bc56e9d6fa02bc88ec">EventHook</a>
</li>
<li>doEvents()
: <a class="el" href="interface_u_i.php#ad3d9b6673410aa22403cbb513c55ee4a">UI</a>
</li>
</ul>


<h3><a class="anchor" id="index_e"></a>- e -</h3><ul>
<li>exec()
: <a class="el" href="interface_f_i_l_e.php#a7c00c5f992f9567ec7b69d6e3cf25934">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_f"></a>- f -</h3><ul>
<li>fileExists()
: <a class="el" href="interface_f_i_l_e.php#af3294a406276bff3baad8bcb719aab66">FILE</a>
</li>
<li>folderExists()
: <a class="el" href="interface_f_i_l_e.php#a93e2667c7fe3288e3e2db065fcc9f063">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_g"></a>- g -</h3><ul>
<li>get()
: <a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#ad28f052945833b0267c4353afcbf58eb">LOCALIZATION</a>
</li>
<li>getAcceptLanguages()
: <a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#a0162e8ff61641568734b65adec1ad183">LOCALIZATION</a>
</li>
<li>getAppDataFolder()
: <a class="el" href="interface_f_i_l_e.php#a6181d0579cb9654e86cd506737f0475f">FILE</a>
</li>
<li>getDraggables()
: <a class="el" href="interface_u_i.php#a036ec67a95716f85c0be9e723ac4782d">UI</a>
</li>
<li>getExeFilename()
: <a class="el" href="interface_f_i_l_e.php#a943b822f2c3c6f32774e389330bd6a63">FILE</a>
</li>
<li>getExeFolder()
: <a class="el" href="interface_f_i_l_e.php#ad1a8f26a2cf973ae0ddffc624a479e62">FILE</a>
</li>
<li>getJSVariable()
: <a class="el" href="interface_browser_window.php#a280f7ebe3df2ce474a5852d5cd2191d7">BrowserWindow</a>
</li>
<li>getJSWindow()
: <a class="el" href="interface_browser_window.php#ad2d8da20a97eb156c4c54ae708c6a389">BrowserWindow</a>
</li>
<li>getLang()
: <a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#ab8161b47b743b715de4683c838c60d4d">LOCALIZATION</a>
</li>
<li>getObject()
: <a class="el" href="interface_c_o_m.php#aa5d75d3298d5de451ecbead91d92b32d">COM</a>
</li>
<li>getParentFolder()
: <a class="el" href="interface_f_i_l_e.php#a7366dfecccd6c0170f9fe6c4709aad25">FILE</a>
</li>
<li>getProgramFolder()
: <a class="el" href="interface_f_i_l_e.php#a42f314c1d5c8bc86abf76ecb850039c0">FILE</a>
</li>
<li>getWindowPlacement()
: <a class="el" href="interface_u_i.php#a8077b95470f71884d59a6d5f09f29b5b">UI</a>
</li>
<li>getWindowRect()
: <a class="el" href="interface_u_i.php#afe21d5b455eddf90a3260f387bb94379">UI</a>
</li>
</ul>


<h3><a class="anchor" id="index_h"></a>- h -</h3><ul>
<li>hookMessage()
: <a class="el" href="interface_window_hook.php#a7ae2597fb98a0a318f2a9f6295c6bc17">WindowHook</a>
</li>
</ul>


<h3><a class="anchor" id="index_i"></a>- i -</h3><ul>
<li>iniReadInt()
: <a class="el" href="interface_f_i_l_e.php#a0f1894aaa83f22c87ac4cfc0f3ff05be">FILE</a>
</li>
<li>iniReadStr()
: <a class="el" href="interface_f_i_l_e.php#a3130fd3652e1b86373b61cfc0348981e">FILE</a>
</li>
<li>iniWrite()
: <a class="el" href="interface_f_i_l_e.php#ab82c10757856fbd93d04603ce226cb38">FILE</a>
</li>
<li>interface2Object()
: <a class="el" href="interface_c_o_m.php#a9742cc74cdf0445008d4adb2adbaa0d3">COM</a>
</li>
<li>isClosed()
: <a class="el" href="interface_browser_window.php#a4bc7c90e1f4048197bac2c5ff797e9be">BrowserWindow</a>
</li>
<li>isFileUrl()
: <a class="el" href="interface_f_i_l_e.php#a0c351eaed10231b01698938550e31cbe">FILE</a>
</li>
<li>isUrl()
: <a class="el" href="interface_f_i_l_e.php#a58b7576336d5c990156ccc211bc09c3a">FILE</a>
</li>
<li>item()
: <a class="el" href="interface_enumerator.php#a7ceba38a65084b6f9b35b5c930ca0420">Enumerator</a>
</li>
</ul>


<h3><a class="anchor" id="index_k"></a>- k -</h3><ul>
<li>kill()
: <a class="el" href="interface_thread.php#a980d8518a01dac55c30b0fb2fb894eba">Thread</a>
</li>
</ul>


<h3><a class="anchor" id="index_l"></a>- l -</h3><ul>
<li>listFolder()
: <a class="el" href="interface_f_i_l_e.php#af20f5de0d692771dafbeef7fb57fc500">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_m"></a>- m -</h3><ul>
<li>moveFirst()
: <a class="el" href="interface_enumerator.php#a6ee9f6f3140a53b0805c17ff3155d2f1">Enumerator</a>
</li>
<li>moveNext()
: <a class="el" href="interface_enumerator.php#aa8ea58356f7061aa51df936b16acb242">Enumerator</a>
</li>
<li>moveWindow()
: <a class="el" href="interface_u_i.php#a48bb86d6512ddef0a89997f6f26b28bb">UI</a>
</li>
<li>msgBox()
: <a class="el" href="interface_u_i.php#ae4029da3a7b30a44c2a93b186146e3ae">UI</a>
</li>
</ul>


<h3><a class="anchor" id="index_n"></a>- n -</h3><ul>
<li>newBuffer()
: <a class="el" href="interface_dll_call.php#af9c99ab123bbf569e623a9c5e5c9f40e">DllCall</a>
</li>
<li>newStruct()
: <a class="el" href="interface_dll_call.php#ac5fb73dfc65171de9e56b090a56b1269">DllCall</a>
</li>
<li>newThread()
: <a class="el" href="interface_threading.php#ab83b569dcb6b1ed35d6e9f13a8376a64">Threading</a>
</li>
<li>newWindow()
: <a class="el" href="interface_u_i.php#a1affe0f3629c5b39d93ba05fd54fc3fc">UI</a>
</li>
<li>normalizeUrl()
: <a class="el" href="interface_f_i_l_e.php#a841b182f6e93f43af7ba128d020dcea7">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_p"></a>- p -</h3><ul>
<li>pathToUrl()
: <a class="el" href="interface_f_i_l_e.php#ad6e821755d0d8b859a69853bb8b3144d">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_r"></a>- r -</h3><ul>
<li>readFileUTF8()
: <a class="el" href="interface_f_i_l_e.php#af18bb442d4a17a21806d850fab3dcb99">FILE</a>
</li>
<li>readUrl()
: <a class="el" href="interface_f_i_l_e.php#a755585f93d7b4fdc84e455fe334a7e29">FILE</a>
</li>
<li>regDelete()
: <a class="el" href="interface_f_i_l_e.php#aa9ccfdf0c38f87f504a5ae2f763977b7">FILE</a>
</li>
<li>regRead()
: <a class="el" href="interface_f_i_l_e.php#ae283d76f4b92fd2f67e1db96f607e70c">FILE</a>
</li>
<li>regWrite()
: <a class="el" href="interface_f_i_l_e.php#a461f0e68e5dc507ba50ac94d56a2cfcd">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_s"></a>- s -</h3><ul>
<li>setDraggables()
: <a class="el" href="interface_u_i.php#a07804c8c056dedcec3467bc1c9470db4">UI</a>
</li>
<li>setLang()
: <a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#acaf64f0e414c32bfa3c5cee215b06373">LOCALIZATION</a>
</li>
<li>setPath()
: <a class="el" href="interface_l_o_c_a_l_i_z_a_t_i_o_n.php#a494b7408816f0e6545fe409d7f14a1a6">LOCALIZATION</a>
</li>
<li>setWindowPlacement()
: <a class="el" href="interface_u_i.php#a3fdde78a1c8ea2a61bac248bfc85e9df">UI</a>
</li>
<li>showTitleBar()
: <a class="el" href="interface_u_i.php#a8661d51c7e5389632e89177abfd92a45">UI</a>
</li>
<li>sleep()
: <a class="el" href="interface_threading.php#a2f94dee6d866d46d1f949359c765f704">Threading</a>
</li>
</ul>


<h3><a class="anchor" id="index_t"></a>- t -</h3><ul>
<li>trust()
: <a class="el" href="interfacelocal_j_s.php#a638f18884615ddd3e7cc901a3302f931">localJS</a>
</li>
</ul>


<h3><a class="anchor" id="index_u"></a>- u -</h3><ul>
<li>unhook()
: <a class="el" href="interface_window_hook.php#a916fade963fb61259cb414f46d6f0bb3">WindowHook</a>
</li>
<li>unhookMessage()
: <a class="el" href="interface_window_hook.php#abaa21865555f3152ae8185807c50cd25">WindowHook</a>
</li>
<li>updateTitle()
: <a class="el" href="interface_u_i.php#a733cb08eb4bc17051512573d8d67d388">UI</a>
</li>
<li>urlToPath()
: <a class="el" href="interface_f_i_l_e.php#af4d5763f007ae57760e4903712f323f3">FILE</a>
</li>
</ul>


<h3><a class="anchor" id="index_w"></a>- w -</h3><ul>
<li>writeFileUTF8()
: <a class="el" href="interface_f_i_l_e.php#a79aabfb4240680c61bf91440ff6e9823">FILE</a>
</li>
</ul>
</div>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
