<?php
require_once('../../_config.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<?php include_once($base_path.'/_include/common_header_part1.php'); ?>
<title>LocalJS: Getting Started</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>fonts/fonts-min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>grids/grids-min.css"/>
<?php include_once($base_path.'/_include/common_header_part2.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Home</span></a></li>
      <li class="current"><a href="pages.php"><span>Getting&#160;Started</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>
      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>Getting Started </h1>  </div>
</div>
<div class="contents">
<div align="center"><em>Prev:</em> <a class="el" href="index.php#localjs_overview">LocalJS Overview</a> | <em>Next:</em> <a class="el" href="howto.php">How To ...</a> | <a class="el" href="group___j_s_objects.php">LocalJS Objects (Advanced)</a> | <a class="el" href="index.php">Document Home</a></div><p>Suggested steps to get started:</p>
<ul>
<li>Browse <a class="el" href="howto.php">How To ...</a> list to get a basic understanding of LocalJS. </li>
<li>Download the <a href="http://sourceforge.net/projects/localjs/files/" target="_blank">demo application</a> on site and read the JavaScript code included. Use this documentation as a tool to understand the <a href="http://sourceforge.net/projects/localjs/files/" target="_blank">demo application</a>. <dl class="user"><dt><b></b></dt><dd>The <a href="http://sourceforge.net/projects/localjs/files/" target="_blank">demo application</a> is divided into multiple sections, focusing on different topics. The JavaScript source code for each section is separated into different files. It's easy to match up. </dd></dl>
</li>
<li>Finally, take a look at <a class="el" href="group___host_a_p_i.php">LocalJS Hosting API</a>, as well as the source code for the bootstrap program included in the <a href="http://sourceforge.net/projects/localjs/files/" target="_blank">demo</a>.</li>
</ul>
<div align="center"><em>Prev:</em> <a class="el" href="index.php#localjs_overview">LocalJS Overview</a> | <em>Next:</em> <a class="el" href="howto.php">How To ...</a> | <a class="el" href="group___j_s_objects.php">LocalJS Objects (Advanced)</a> | <a class="el" href="index.php">Document Home</a></div> </div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
