<?php
require_once('../../_config.php');
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/xhtml;charset=UTF-8"/>
<?php include_once($base_path.'/_include/common_header_part1.php'); ?>
<title>LocalJS: JavaScript Tutorials</title>
<link href="tabs.css" rel="stylesheet" type="text/css"/>
<link href="doxygen.css" rel="stylesheet" type="text/css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>fonts/fonts-min.css"/>
<link rel="stylesheet" type="text/css" href="<?php echo $yui_root; ?>grids/grids-min.css"/>
<?php include_once($base_path.'/_include/common_header_part2.php'); ?>
<!-- Generated by Doxygen 1.7.2 -->
<script type="text/javascript"><!--
var searchBox = new SearchBox("searchBox", "search",false,'Search');
--></script>
<div class="navigation" id="top">
  <div class="tabs">
    <ul class="tablist">
      <li><a href="index.php"><span>Home</span></a></li>
      <li class="current"><a href="pages.php"><span>Getting&#160;Started</span></a></li>
      <li><a href="modules.php"><span>Modules</span></a></li>
      <li><a href="namespaces.php"><span>Namespaces</span></a></li>
      <li><a href="annotated.php"><span>Classes</span></a></li>
      <li id="searchli">
        <div id="MSearchBox" class="MSearchBoxInactive">
          <span class="left">
            <form id="FSearchBox" action="search.php" method="get">
              <img id="MSearchSelect" src="search/mag.png" alt=""/>
              <input type="text" id="MSearchField" name="query" value="Search" size="20" accesskey="S" 
                     onfocus="searchBox.OnSearchFieldFocus(true)" 
                     onblur="searchBox.OnSearchFieldFocus(false)"/>
            </form>
          </span><span class="right"></span>
        </div>
      </li>
    </ul>
  </div>
</div>
<div class="header">
  <div class="headertitle">
<h1>JavaScript Tutorials </h1>  </div>
</div>
<div class="contents">
<div align="center"><em>Prev:</em> <a class="el" href="tutorial_js4cpp.php">JavaScript Jump Start For C++ Programmers</a> | <a class="el" href="group___j_s_objects.php">LocalJS Objects (Advanced)</a> | <a class="el" href="index.php">Document Home</a> | <a href="http://sourceforge.net/projects/localjs/files/" target="_blank">Download demo application</a></div><ul>
<li><a href="http://www.javascriptkit.com/javatutors/oopjs.shtml" target="_blank">JavaScript and OOP</a> </li>
<li><a href="http://www.javascriptkit.com/javatutors/object.shtml" target="_blank">Creating custom objects in JavaScript</a> </li>
<li><a href="http://www.javascriptkit.com/javatutors/proto.shtml" target="_blank">The prototype object of JavaScript 1.1</a> </li>
<li>A more completed list: <a href="http://www.javascriptkit.com/javatutors/" target="_blank">JavaScript Tutorials</a></li>
</ul>
<div align="center"><em>Prev:</em> <a class="el" href="tutorial_js4cpp.php">JavaScript Jump Start For C++ Programmers</a> | <a class="el" href="group___j_s_objects.php">LocalJS Objects (Advanced)</a> | <a class="el" href="index.php">Document Home</a> | <a href="http://sourceforge.net/projects/localjs/files/" target="_blank">Download demo application</a></div> </div>
<hr class="footer"/>
<?php include_once($base_path.'/_include/common_footer.php'); ?>
</html>
